### ISSUE TITLE
convert from English numbers to Arabic numbers

### ISSUE THREAD

**Issue by devfalah** [FlutterQueen/readable#11]
**Is your feature request related to a problem? Please describe.**
convert from English numbers to Arabic numbers & convert from Arabic numbers to English numbers 

"1".toArabicNumbers();//'١'
'١'.toEnglishNumbers();//'1'

**Comment by maxzod** [comment]
i have already built it in `nations` package 
https://github.com/FlutterQueen/nations/blob/b46a7f36988813b0f88576b652fec8a0e48b3d73/lib/src/helpers/string.dart#L6
https://github.com/FlutterQueen/nations/blob/b46a7f36988813b0f88576b652fec8a0e48b3d73/lib/src/helpers/string.dart#L20
https://github.com/FlutterQueen/nations/blob/b46a7f36988813b0f88576b652fec8a0e48b3d73/lib/src/helpers/string.dart#L35

we should leave them there since the are localization related
